name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
      - uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6
      - uses: actions/cache@v3.0.5
        env:
          cache-name: maven-cache
        with:
          path: ~/.m2
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
      - run: REDIS_URL=redis://127.0.0.1:6379/0 clojure -A:test -M -m kaocha.runner
